INSERT INTO STUDENT_DETAILS values(101,'Chris',1);
INSERT INTO STUDENT_DETAILS values(102,'Charles',3);
INSERT INTO STUDENT_DETAILS values(103,'Mark',2);
INSERT INTO STUDENT_DETAILS values(104,'Steve',4);