server:
  port: 9090
  
spring:
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
      
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testDB
    username: sa
    password: 