INSERT INTO GENDER_DETAILS values(1,'Male')
INSERT INTO GENDER_DETAILS values(2,'Female')

INSERT INTO COURSE_DETAILS values(1,'Python')
INSERT INTO COURSE_DETAILS values(2,'Java')
INSERT INTO COURSE_DETAILS values(3,'.NET Framework')
INSERT INTO COURSE_DETAILS values(4,'Angular')
INSERT INTO COURSE_DETAILS values(5,'React JS')
INSERT INTO COURSE_DETAILS values(6,'PHP')

INSERT INTO COURSE_TIMINGS values(1, 'Morning')
INSERT INTO COURSE_TIMINGS values(2, 'Afternoon')
INSERT INTO COURSE_TIMINGS values(3, 'Evening')